export const NEXT_QUESTION = "NEXT_QUESTION"
export const END_QUIZ = "END_QUIZ"
export const RETURN_TO_QUIZ = "RETURN_TO_QUIZ"
export const ADD_NEW_QUIZ = "ADD_NEW_QUIZ"

//CREATE QUIZ
export const HANDLE_CHANGE_QUIZ_NAME = "HANDLE_CHANGE_QUIZ_NAME"
export const HANDLE_CHANGE_QUESTION = "HANDLE_CHANGE_QUESTION"
export const HANDLE_CHANGE_ANSWER_ONE = "HANDLE_CHANGE_ANSWER_ONE"
export const HANDLE_CHANGE_ANSWER_TWO = "HANDLE_CHANGE_ANSWER_TWO"
export const HANDLE_CHANGE_ANSWER_THREE = "HANDLE_CHANGE_ANSWER_THREE"
export const HANDLE_CHANGE_ANSWER_FOUR = "HANDLE_CHANGE_ANSWER_FOUR"
export const HANDLE_CHANGE_SELECT = "HANDLE_CHANGE_SELECT"
export const ADD_QUESTION_TO_QUIZ = "ADD_QUESTION_TO_QUIZ"
export const ADD_QUIZ_NAME = "ADD_QUIZ_NAME"
export const CLEAR_VALUE_QUIZ_NAME = "CLEAR_VALUE_QUIZ_NAME"

